// This file is generated by Slice Machine. Update with care!

import BmiCalculator from './BmiCalculator';
import Counter from './Counter';
import Gallery from './Gallery';
import Hero from './Hero';
import Image from './Image';
import ImageCards from './ImageCards';
import PricingPackages from './PricingPackages';
import Quote from './Quote';
import Reviews from './Reviews';
import Sidebar from './Sidebar';
import Text from './Text';
import TextWithImage from './TextWithImage';

export {
	BmiCalculator,
	Counter,
	Gallery,
	Hero,
	Image,
	ImageCards,
	PricingPackages,
	Quote,
	Reviews,
	Sidebar,
	Text,
	TextWithImage,
};

export const components = {
	bmi_calculator: BmiCalculator,
	counter: Counter,
	gallery: Gallery,
	hero: Hero,
	image: Image,
	image_cards: ImageCards,
	pricing_packages: PricingPackages,
	quote: Quote,
	reviews: Reviews,
	sidebar: Sidebar,
	text: Text,
	text_with_image: TextWithImage,
};
